;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-abbr-reader.ss" "lang")((modname bst) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #t)))
(require spd/tags)

(require "provide.rkt")
(provide (matching-identifiers-out #rx"^((?!--).)*$" (all-defined-out)))

(require "common.rkt")
(@htdd Colour Vector Euler Triangle)

;;
;; BST.rkt
;;
;; Binary search tree data definitions and utility functions
;; since BSL doesn't have a collection with faster than O(n) lookup
;;


;;
;; DATA DEFINITIONS
;;


(@htdd BST)
(define-struct bst-node (key value left right))
;; BST is one of:
;;  - false
;;  - (make-node Natural X BST BST)
;; interp. a node in a binary search tree, with its key/value and children
;;         (generics don't exist in SPD but I don't really care)
;; CONSTRAINT: all keys in left must be less than key;
;;             all keys in right must be greater than key;
;;             all keys must be unique
(define EMPTY-BST false)
(define BST1 (make-bst-node 6 6 false false))
(define BST2 (make-bst-node 5 5 (make-bst-node 4 4 false false) false))
(define BST3 (make-bst-node 3 3
                            (make-bst-node 1 1
                                           (make-bst-node 0 0 false false)
                                           (make-bst-node 2 2 false false))
                            false)) ;example of a BST with optimal height;
;                                   ;could be generated by construct-bst
(define BST4 (make-bst-node 2 2
                            (make-bst-node 0 0
                                           false
                                           (make-bst-node 1 1 false false))
                            (make-bst-node 3 3 false false))) ;BST that could
;                                                             ;not be generated
(define BST5 (make-bst-node 3 3
                            (make-bst-node 2 2
                                           (make-bst-node 0 0
                                                          false
                                                          (make-bst-node 1 1
                                                                         false
                                                                         false))
                                           false)
                            false)) ;suboptimal BST example

(@dd-template-rules one-of          ;2 cases
                    atomic-distinct ;false
                    compound        ;(make-node Natural X BST BST)
                    self-ref        ;(node-left BST) is BST
                    self-ref)       ;(node-right BST) is BST

(define (fn-for-bst bst)
  (cond [(false? bst)
         (...)]
        [else
         (... (bst-node-key bst)
              (bst-node-value bst)
              (fn-for-bst (bst-node-left bst))
              (fn-for-bst (bst-node-right bst)))]))


;;
;; FUNCTIONS
;;


(@htdf lookup-bst)
(@signature BST Natural -> X or false)
;; produce value of node in BST with given key, or false if it does not exist
(check-expect (lookup-bst BST3 2) 2)
(check-expect (lookup-bst BST5 1) 1)
(check-expect (lookup-bst BST4 0) 0)
(check-expect (lookup-bst BST4 4) false)

(@template-origin BST)

(define (lookup-bst tree key)
  (cond [(false? tree)
         false]
        [else
         (cond [(= key (bst-node-key tree))
                (bst-node-value tree)]
               [(< key (bst-node-key tree))
                (lookup-bst (bst-node-left tree) key)]
               [else
                (lookup-bst (bst-node-right tree) key)])]))


#|
O(n) BST construction from a singly linked list in one pass without arrays
Some notes:
- BSL doesn't have arrays/vectors, which would have made BST construction much
  easier (and eliminated the need of them in the first place).
- Generating the pattern for the BST takes O(n) time (one call to reverse,
  as well as O(n) total calls to cons by append).
- The actual traversal performs one pass over the list, mostly calling
  non-recursive (O(1)) functions on each element for total complexity O(n).
- The only recursive functions called are drop and fold. However, the total
  number of calls (recursive or non-recursive) to each function is guaranteed
  to be less than the number of elements in the list.
- Hence the overall time complexity should probably be O(n), which is optimal.
- Note that this does not necessarily produce complete or balanced binary trees.
  This is not really important since we will not be inserting any nodes.
|#


(@htdf construct-bst construct-bst--acc)
(@signature (listof X) Natural -> BST)
;; construct binary search tree from given list of known length
(check-expect (construct-bst empty 0) EMPTY-BST)
;; As the behaviour of this implementation for large lists is difficult to infer
;; and manually creating such test cases is impractical, this function is tested
;; against a naive genrec implementation which is defined later in this file.
;; Unfortunately map (and other second-order functions) aren't supported in BSL.
(check-expect (construct-bst (make-list--test 10000) 10000)
              (construct-bst-naive--test (make-list--test 10000) 10000))
(check-expect (construct-bst (make-list--test 12345) 12345)
              (construct-bst-naive--test (make-list--test 12345) 12345))
(check-expect (construct-bst (make-list--test 15360) 15360)
              (construct-bst-naive--test (make-list--test 15360) 15360))
(check-expect (construct-bst (make-list--test 15361) 15361)
              (construct-bst-naive--test (make-list--test 15361) 15361))
(check-expect (construct-bst (make-list--test 16383) 16383)
              (construct-bst-naive--test (make-list--test 16383) 16383))
(check-expect (construct-bst (make-list--test 16384) 16384)
              (construct-bst-naive--test (make-list--test 16384) 16384))
(check-expect (construct-bst (make-list--test 16404) 16404)
              (construct-bst-naive--test (make-list--test 16404) 16404))

(@template-origin accumulator)

(define (construct-bst lst count)
  (cond [(empty? lst)
         EMPTY-BST]
        [else
         (construct-bst--acc (rest lst)
                             (rest (bst-pattern count)) 0
                             empty 1 empty
                             (make-bst-node 0 (first lst) false false)
                             empty)]))

(@template-origin (listof X) accumulator)

;; heights is (listof Natural)
;; INVARIANT: the height of every node to be created from the corresponding
;;            element in lst; a single node has height 0
;;
;; last-height is Natural
;; INVARIANT: the height of the last element of lst seen
;;
;; working-heights is (listof Natural)
;; INVARIANT: the maximum node height of every BST in imperfect
;;
;; index is Natural
;; INVARIANT: the zero-based index of the current element of lst
;;
;; fold-counts is (listof Natural)
;; INVARIANT: the sequence of numbers of fold operations required to construct
;;            a complete binary search tree from perfect and trees in imperfect
;;
;; perfect is BST
;; INVARIANT: the last perfect binary search tree constructed that has not
;;            been added to a larger tree; false if it does not exist
;;
;; imperfect is (listof BST)
;; INVARIANT: the list of all imperfect binary search trees constructed,
;;            in reverse order of construction
(define (construct-bst--acc lst heights last-height working-heights
                            index fold-counts perfect imperfect)
  (cond [(empty? lst)
         (if (empty? imperfect)
             perfect
             (fold perfect imperfect
                   (first (reverse fold-counts))))]
        [else
         (cond [(zero? (first heights))
                (if (= last-height 1)
                    (construct-bst--acc (rest lst) (rest heights) 0
                                        (drop working-heights
                                              (first fold-counts))
                                        (add1 index) (rest fold-counts)
                                        (fold (make-bst-node index (first lst)
                                                             false false)
                                              imperfect (first fold-counts))
                                        (drop imperfect (first fold-counts)))
                    (construct-bst--acc (rest lst) (rest heights) 0
                                        working-heights
                                        (add1 index) fold-counts
                                        (make-bst-node index (first lst)
                                                       false false)
                                        imperfect))]
               [(or (empty? imperfect)
                    (not (= (first heights) (sub1 (first working-heights)))))
                (construct-bst--acc (rest lst) (rest heights) (first heights)
                                    (cons (first heights) working-heights)
                                    (add1 index) (cons (first heights)
                                                       fold-counts)
                                    false
                                    (cons (make-bst-node index (first lst)
                                                         perfect false)
                                          imperfect))]
               [else
                (construct-bst--acc (rest lst) (rest heights) (first heights)
                                    (cons (first heights) working-heights)
                                    (add1 index) fold-counts
                                    false
                                    (cons (make-bst-node index (first lst)
                                                         perfect false)
                                          imperfect))])]))



(@htdf fold)
(@signature BST (listof BST) Natural -> BST)
;; recursively attach child to (first ancestors) until empty, or count is 0
(check-expect (fold BST1 empty 0) BST1)
(check-expect (fold BST1 empty 3) BST1)
(check-expect (fold (make-bst-node 4 4 false false) (list BST3) 0)
              (make-bst-node 4 4 false false))
(check-expect (fold (make-bst-node 4 4 false false) (list BST3) 1)
              (make-bst-node 3 3
                             (make-bst-node 1 1
                                            (make-bst-node 0 0 false false)
                                            (make-bst-node 2 2 false false))
                             (make-bst-node 4 4 false false)))
(check-expect (fold (make-bst-node 4 4 false false) (list BST3) 2)
              (make-bst-node 3 3
                             (make-bst-node 1 1
                                            (make-bst-node 0 0 false false)
                                            (make-bst-node 2 2 false false))
                             (make-bst-node 4 4 false false)))
(check-expect (fold BST1 (list BST2 BST3) 2)
              (make-bst-node 3 3
                             (make-bst-node 1 1
                                            (make-bst-node 0 0 false false)
                                            (make-bst-node 2 2 false false))
                             (make-bst-node 5 5
                                            (make-bst-node 4 4 false false)
                                            (make-bst-node 6 6 false false))))
(check-expect (fold (make-bst-node 10 10 false false)
                    (list
                     (make-bst-node 9 9 (make-bst-node 8 8 false false) false)
                     (make-bst-node 7 7 (fold BST1 (list BST2 BST3) 2) false))
                    1)
              (make-bst-node 9 9
                             (make-bst-node 8 8 false false)
                             (make-bst-node 10 10 false false)))
(check-expect (fold (make-bst-node 10 10 false false)
                    (list
                     (make-bst-node 9 9 (make-bst-node 8 8 false false) false)
                     (make-bst-node 7 7 (fold BST1 (list BST2 BST3) 2) false))
                    3)
              (make-bst-node 7 7
                             (fold BST1 (list BST2 BST3) 2)
                             (make-bst-node 9 9
                                            (make-bst-node 8 8 false false)
                                            (make-bst-node 10 10 false false))))

(@template-origin 2-one-of accumulator)

#|
             count    0              (add1 Natural)
ancestors

empty                 child [0]      child [0]

(cons BST             child [0]      (fold (set-right (first ancestors) child)
      (listof BST))                        (rest ancestors) (sub1 count)) [1]
|#

;; child is BST
;; INVARIANT: the next binary search tree that can be attached
(define (fold child ancestors count)
  (cond [(or (zero? count) (empty? ancestors)) ;[0]
         child]
        [else                                  ;[1]
         (fold (set-right (first ancestors) child)
               (rest ancestors) (sub1 count))]))



(@htdf set-right)
(@signature BST BST -> BST)
;; produce first BST with right child set to second BST
;; CONSTRAINT: first BST must be nonempty
(check-expect (set-right BST3 false) BST3)
(check-expect (set-right BST3 (make-bst-node 5 5
                                             (make-bst-node 4 4 false false)
                                             (make-bst-node 6 6 false false)))
              (make-bst-node 3 3
                             (make-bst-node 1 1
                                            (make-bst-node 0 0 false false)
                                            (make-bst-node 2 2 false false))
                             (make-bst-node 5 5
                                            (make-bst-node 4 4 false false)
                                            (make-bst-node 6 6 false false))))
(check-expect (set-right BST4 false)
              (make-bst-node 2 2
                             (make-bst-node 0 0
                                            false
                                            (make-bst-node 1 1 false false))
                             false))

(@template-origin BST)

(define (set-right bst right)
  (cond [(false? bst)
         (error "First BST must be nonempty")]
        [else
         (make-bst-node (bst-node-key bst)
                        (bst-node-value bst)
                        (bst-node-left bst)
                        right)]))



(@htdf bst-pattern)
(@signature Natural -> (listof Natural))
;; produce list of BST node heights for a list with count elements
;; CONSTRAINT: count must be nonzero
(check-expect (bst-pattern 1)  (list 0))
(check-expect (bst-pattern 3)  (list 0 1 0))
(check-expect (bst-pattern 10) (list 0 1 0 2 0 1 0 3 0 1))
(check-expect (bst-pattern 15) (list 0 1 0 2 0 1 0 3 0 1 0 2 0 1 0))
;; This really just generates the zero-based ruler sequence (OEIS: A007814)

(@template-origin fn-composition)

(define (bst-pattern count)
  (height->bst-pattern (floor (log2 count)) count))



(@htdf height->bst-pattern height->bst-pattern--acc)
(@signature Natural -> (listof Natural))
;; produce list of BST node heights for a BST with given height trimmed to count
(check-expect (height->bst-pattern 1 1)  (list 0))
(check-expect (height->bst-pattern 2 3)  (list 0 1 0))
(check-expect (height->bst-pattern 4 10) (list 0 1 0 2 0 1 0 3 0 1))
(check-expect (height->bst-pattern 4 15) (list 0 1 0 2 0 1 0 3 0 1 0 2 0 1 0))

(@template-origin accumulator)

(define (height->bst-pattern height count)
  (reverse (drop (height->bst-pattern--acc height 0 empty)
                 (- (sub1 (expt 2 (add1 height))) count))))

(@template-origin genrec accumulator)

;; height is Natural
;; INVARIANT: height of the current part of the BST pattern being generated
;;
;; last is (listof Natural)
;; INVARIANT: previously generated part of the pattern, up to and not including
;;            the current height; represents deeper parts of the BST
;;
;; Genrec info
;; Trivial case:   (= height target)
;; Reduction step: (add1 height)
;; Termination argument:
;;   For natural number target >= 0 and height starting at 0,
;;   adding 1 to height will cause it to eventually reach target
(define (height->bst-pattern--acc target height last)
  (if (= height target)
      (cons-pattern height last)
      (height->bst-pattern--acc target (add1 height)
                                (cons-pattern height last))))



(@htdf cons-pattern)
(@signature Natural (listof Natural) -> (listof Natural))
;; produce next pattern by prepending and appending list to given number
(check-expect (cons-pattern 0 empty) (list 0))
(check-expect (cons-pattern 4 (list 1 2 3)) (list 1 2 3 4 1 2 3))
(check-expect (cons-pattern 3 (list 0 1 0 2 0 1 0))
              (list 0 1 0 2 0 1 0 3 0 1 0 2 0 1 0))

(@template-origin Natural)

(define (cons-pattern n lon)
  (append lon (list n) lon))



(@htdf log2)
(@signature Number -> Number)
;; produce log base 2 of a number
;; CONSTRAINT: the given number must be positive
(check-expect (log2 0.5) -1)
(check-expect (log2 1) 0)
(check-expect (log2 16) 4)
(check-expect (log2 4294967296) 32)
(check-within (log2 10000) 13.28771237954945 DELTA)

(@template-origin Number)

(define (log2 x)
  (inexact->exact (/ (log x) (log 2))))


;;
;; TESTING FUNCTIONS
;;
;; Function names in this section are generally suffixed with --test
;; to prevent them from being exported (by matching-identifiers-out)
;;


(@htdf construct-bst-naive--test construct-bst-naive--acc)
(@signature (listof X) Natural -> BST)
;; construct binary search tree from given list (slow/non-TR implementation)
(check-expect (construct-bst-naive--test empty 0) EMPTY-BST)
(check-expect (construct-bst-naive--test (list 0) 1)
              (make-bst-node 0 0 false false))
(check-expect (construct-bst-naive--test (list 0 1 2 3 4) 5)
              (make-bst-node 3 3
                             (make-bst-node 1 1
                                            (make-bst-node 0 0 false false)
                                            (make-bst-node 2 2 false false))
                             (make-bst-node 4 4 false false)))
(check-expect (construct-bst-naive--test (list 0 1 2 3 4 5 6) 7)
              (make-bst-node 3 3
                             (make-bst-node 1 1
                                            (make-bst-node 0 0 false false)
                                            (make-bst-node 2 2 false false))
                             (make-bst-node 5 5
                                            (make-bst-node 4 4 false false)
                                            (make-bst-node 6 6 false false))))

(@template-origin accumulator)

(define (construct-bst-naive--test lst count)
  (construct-bst-naive--acc lst 0))

(@template-origin genrec accumulator)

;; Time complexity: lol
;;
;; key is Natural
;; INVARIANT: the key of the first element of lst
;;
;; Genrec info
;; Trivial case:   (empty? lst)
;; Reduction step: (take lst (sub1 (expt 2 (floor (log2 (length lst)))))),
;;                 (drop lst (expt 2 (floor (log2 (length lst)))))
;; Termination argument:
;;   (sub1 (expt 2 (floor (log2 (length lst))))) < (length lst) and
;;   (expt 2 (floor (log2 (length lst)))) > 0;
;;   thus the lists generated by the reduction step are necessarily proper
;;   subsets of the original list, and repeatedly taking proper subsets of
;;   a finite list will eventually result in an empty list (trivial case).
(define (construct-bst-naive--acc lst key)
  (if (empty? lst)
      EMPTY-BST
      (make-bst-node (+ key (sub1 (expt 2 (floor (log2 (length lst))))))
                     (list-ref lst (sub1 (expt 2 (floor (log2 (length lst))))))
                     (construct-bst-naive--acc
                      (take lst (sub1 (expt 2 (floor (log2 (length lst))))))
                      key)
                     (construct-bst-naive--acc
                      (drop lst (expt 2 (floor (log2 (length lst)))))
                      (+ key (expt 2 (floor (log2 (length lst)))))))))



(@htdf make-list--test)
(@signature Natural -> (listof Natural))
;; produce ascending list of nonnegative integers up to but not including n
(check-expect (make-list--test 0)  (list))
(check-expect (make-list--test 1)  (list 0))
(check-expect (make-list--test 10) (list 0 1 2 3 4 5 6 7 8 9))
(check-expect (make-list--test 16) (list 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15))

(@template-origin accumulator)

(define (make-list--test n)
  (make-list--acc n empty))

(@template-origin Natural accumulator)

;; rsf is (listof Natural)
;; INVARIANT: all numbers between the current number and n, excluding n
(define (make-list--acc n rsf)
  (cond [(zero? n)
         rsf]
        [else
         (make-list--acc (sub1 n) (cons (sub1 n) rsf))]))



(@htdf bst-time-regular--test)
(@signature Natural -> Natural)
;; produce time to construct a BST with n elements
;; (tests not possible)

(@template-origin Natural)

(define (bst-time-regular--test n)
  (- (- (first (list (current-milliseconds)
                     (construct-bst (make-list--test n) n)))
        (current-milliseconds))))



(@htdf bst-time-naive--test)
(@signature Natural -> Natural)
;; produce time to construct a BST with n elements using naive implementation
;; (tests not possible)

(@template-origin Natural)

(define (bst-time-naive--test n)
  (- (- (first (list (current-milliseconds)
                     (construct-bst-naive--test (make-list--test n) n)))
        (current-milliseconds))))
